"""create_initial_tables

Revision ID: 7a1e7d281c5b
Revises: 
Create Date: 2026-03-26 11:53:16.944476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a1e7d281c5b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('monthly_income', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('user', 'admin', name='userrole'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username'),
    schema='LoanHub'
    )
    op.create_index(op.f('ix_LoanHub_users_id'), 'users', ['id'], unique=False, schema='LoanHub')
    op.create_table('loans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.Enum('personal', 'education', 'home', 'vehicle', 'business', name='loanpurpose'), nullable=False),
    sa.Column('tenure_months', sa.Integer(), nullable=False),
    sa.Column('employment_status', sa.Enum('employed', 'self_employed', 'unemployed', 'student', name='employmentstatus'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='loanstatus'), nullable=True),
    sa.Column('admin_remarks', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.String(length=50), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('credit_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['LoanHub.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='LoanHub'
    )
    op.create_index(op.f('ix_LoanHub_loans_id'), 'loans', ['id'], unique=False, schema='LoanHub')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('ix_LoanHub_loans_id'), table_name='loans', schema='LoanHub')
    # op.drop_table('loans', schema='LoanHub')
    # op.drop_index(op.f('ix_LoanHub_users_id'), table_name='users', schema='LoanHub')
    # op.drop_table('users', schema='LoanHub')
    # ### end Alembic commands ###
